In [3]:
import pandas as pd

In [3]:
pd.__version__

'3.0.2'

In [4]:
#设置输出最多为10行
pd.options.display.max_rows = 10

In [6]:
#设置输出最多列
pd.options.display.max_columns = 10

In [7]:
#series对象创建,一维数组
data = pd.Series([1,2,3,4,5,6,7,8,9])

In [8]:
#获取索引index，数据values
print(data.index)
print(data.values)

RangeIndex(start=0, stop=9, step=1)
[1 2 3 4 5 6 7 8 9]

In [9]:
#指定索引
data = pd.Series([1,2,3,4],index=['a','b','c','d'])
data

a    1
b    2
c    3
d    4
dtype: int64

In [10]:
#是呀list指定index
data = pd.Series([1,2,3,4],index=list('abcd'))
data

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
#传入字典创建
data = {'name':'张三','age':23,'sex':'male'}
data

{'name': '张三', 'age': 23, 'sex': 'male'}

In [16]:
#字典创建，并指定index
pd.Series(data,index=['name','age'])

name    张三
age     23
dtype: object

In [2]:
#创建DataFrame对象，传入两个Series对象作为字典的值
p_dict={'name':'张三','age':23,'sex':'male'}
a_dict={'name':'王五','age':27,'sex':'male'}
p_series=pd.Series(p_dict)
a_series=pd.Series(a_dict)
p_series
a_series
#将series对象作为字典的值传入pd.DataFrame
df = pd.DataFrame({'area':a_series,'population':p_series})
df

      area population
name    王五         张三
age     27         23
sex   male       male

In [22]:
df.index
df.values
df.columns

Index(['area', 'population'], dtype='str')

In [11]:
#传入二维数组
import numpy as np
pd.DataFrame(np.random.randint(10,size=(3,4)),index=list('abc'),columns=list('ABCD'))

   A  B  C  D
a  7  5  2  2
b  2  7  2  7
c  3  5  6  1

In [4]:
pd.DataFrame(p_series,columns=['population'])

     population
name         张三
age          23
sex        male

In [1]:
#导入xecel文件数据
pd.read_excel('test.xlsx')

NameError: name 'pd' is not defined

In [2]:
#设置显示的行数
pd.options.display.max_rows = 10
pd.read_excel('test.xlsx')

             学号 性别   身高  体重  支出   开设    课程      软件
0   20260721001  女  155  71  45  不清楚  都未学过      No
1   20260721002  男  156  72  46  不清楚  概率统计  Matlab
2   20260721003  女  157  73  47  不清楚  概率统计  Matlab
3   20260721004  男  158  74  48  不清楚  概率统计  Matlab
4   20260721005  女  159  75  49  不清楚  概率统计  Matlab
..          ... ..  ...  ..  ..  ...   ...     ...
7   20260721008  男  162  78  52  不清楚  概率统计  Matlab
8   20260721009  女  163  79  53  不清楚  概率统计  Matlab
9   20260721010  女  164  80  54  不清楚  概率统计  Matlab
10  20260721011  女  165  81  55  不清楚  概率统计  Matlab
11  20260721012  女  166  82  56  不清楚  概率统计  Matlab

[12 rows x 8 columns]

In [5]:
#读取数据库数据
import pymysql
con = pymysql.connect(host='localhost',user='root',password='root',db='product')#数据库
sql="select * from order_items"#表名
pd.read_sql(sql,con=con)

C:\Users\Administrator.DESKTOP-P5O5RJO\AppData\Local\Temp\ipykernel_16172\2329288521.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(sql,con=con)

   item_id  order_id product_name  quantity   price
0        1       101           手机         1  1500.0
1        2       101          手机壳         2    50.0
2        3       102           电脑         1  2000.0
3        4       103           键盘         1   300.0
4        5       103           鼠标         2   250.0
5        6       104           平板         1  3200.0

In [6]:
#查询order_id为103的订单
sql = "select * from order_items where order_id=103"
pd.read_sql(sql,con=con)

C:\Users\Administrator.DESKTOP-P5O5RJO\AppData\Local\Temp\ipykernel_16172\4035193713.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(sql,con=con)

   item_id  order_id product_name  quantity  price
0        4       103           键盘         1  300.0
1        5       103           鼠标         2  250.0

In [9]:
#保存csv文件
df =pd.read_excel('test.xlsx')
df.to_csv('save_data.csv')

In [12]:
#加上index=false，就不会显示前面的序号了
df.to_csv('save_data.csv',columns=['学号','性别','体重'],index=False)

In [18]:
#保存到excel
df.to_excel("save_data.xlsx")
df.to_excel("save_data1.xlsx",index=False)

In [23]:
df.to_excel('save_data2.xlsx',columns=['学号','性别','体重'],index=False)